# Generated by Django 4.2.15 on 2024-08-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_managers_remove_customuser_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("core.customuser",),
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("core.customuser",),
        ),
        migrations.AddField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[("MANAGER", "Manager"), ("CONTRACTOR", "Contractor")],
                default="CONTRACTOR",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
