# Generated by Django 4.2.15 on 2024-08-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contractor_manager_customuser_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Manager"),
                    ("CONTRACTOR", "Contractor"),
                    ("SUPERUSER", "Superuser"),
                ],
                default="SUPERUSER",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
