# Generated by Django 4.2.15 on 2024-08-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_customuser_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manager",
            options={
                "permissions": (
                    ("can_view_manager_dashboard", "manager access the view"),
                )
            },
        ),
    ]
