# Generated by Django 4.2.15 on 2024-08-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_manager_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manager",
            options={
                "permissions": (
                    ("is_manager", "Can access the manager dashboard view"),
                )
            },
        ),
    ]
