# Generated by Django 4.2.15 on 2024-08-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_manager_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractor",
            options={
                "permissions": (
                    ("is_contractor", "Can access the contractor dashboard view"),
                )
            },
        ),
    ]
