# Generated by Django 4.2.15 on 2024-09-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("1", "level 1"),
                            ("2", "level 2"),
                            ("3", "level 3"),
                            ("4", "level 4"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration", models.DurationField()),
                ("man_hour", models.DurationField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("crew_count", models.PositiveIntegerField(default=1)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew",
                        to="dashboard.project",
                    ),
                ),
            ],
        ),
    ]
