# Generated by Django 4.2.15 on 2024-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_crew_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crew",
            name="crew_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
